// import Head from 'next/head';
import { HomePage } from '../src/components/home/home-page';

export default function Home({ data }: {data:any}) {
  return (
    <div>
   
        <title>Events app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
    

      <HomePage data={data} />
    </div>
  );
}

export async function getServerSideProps() {
  const { events_categories } = await import('/Users/Admin/Desktop/Projects/events_app/data/data.json');
  return {
    props: {
      data: events_categories,
    },
  };
}
